# Generated by Django 5.0.3 on 2024-06-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_user",
                to="account.useraccount",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="phone_number",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="username",
            field=models.CharField(max_length=120),
        ),
    ]
