# Generated by Django 5.0.3 on 2024-06-30 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_user_account_alter_useraccount_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="account_user",
                to="account.useraccount",
            ),
        ),
    ]
