# Generated by Django 5.0.3 on 2024-07-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChannelDiscusion",
            new_name="ChannelDiscussion",
        ),
    ]
