# Generated by Django 5.0.3 on 2024-07-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='channel',
            name='description_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='channel',
            name='description_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='channel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='channel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='channel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
