# Generated by Django 5.0.3 on 2024-07-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0002_rename_channeldiscusion_channeldiscussion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelmessage",
            name="discusions",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="discusions",
        ),
        migrations.DeleteModel(
            name="ChannelDiscussion",
        ),
    ]
